### PR TITLE
Fix 'Click or type to extend your session.' translations in all po files

### PR DESCRIPTION
**Pull request by rdekker1**
…les and compile to mo

### CODE REVIEW

**Comment by mpasternak** [comment]
I don’t like the fact you changed the original translators in PO files. 

Also changing English text is not enough if the translation stays the same (without “or type”)

**Comment by jpic** [comment]
Yes but other translators can update the translation when they need it.

**Comment by rdekker1** [comment]
Technically you’re right (the translation doesn’t match the English string anymore). The original string isn’t necessary anymore, since it’s not in the project anymore. So I’m with jpic; other translators can update the strings later (and until that time, the previous translation will work).

As for the original translators; I didn’t change them, but _Last-Translator_ did get updated (since I am the last translator) by Poedit. It’ll change again if someone updates the translations.

**Comment by mpasternak** [comment]
I hold to my point, if the English text says "click or type" and we just edit that and leave, say, Spanish translation saying just "click" then it's not exactly right. 

On the other hand it's not technically wrong either. 

But but but... it's like "PostgreSQL vs MySQL" kind of thing. When I will see an English text after updating django-session-security for my project, I'll realise that translations have changed and I need to update them. But, if we just change the English text, the translations will become invalid, just in a silent way. 

On the other hand, I do realise that those are just the translations and I don't want to make any trouble here. So technically I'm not exactly against it, but not exactly for it. @jpic , as usual, you decide.

**Comment by jpic** [comment]
Agreed, perhaps we can open a new issue for updating the translation
strings ? perhaps somebody will do it when it matter for them ?

**Comment by rdekker1** [comment]
Fair enough! I’ve updated the Dutch one and reverted the others :)

**Pull request closed without merging**
