### PR TITLE
Allow Redirect to Logout Page on timeout (for SSO Users)

### PR DESCRIPTION
**Pull request by claytondaley**
Definitely need to confirm Chrome-based tests pass before merging.

### CODE REVIEW

**Comment by santosh9991** [comment]
@claytondaley : will try and let you know.

**Comment by ambsw-technology** [comment]
@jpic per [this comment](https://github.com/yourlabs/django-session-security/issues/93#issuecomment-380537506) in #93, this PR is working in production so I propose merging it.  I can rebase if needed.

**Comment by claytondaley** [comment]
@jpic per [this comment](https://github.com/yourlabs/django-session-security/issues/93#issuecomment-380537506) in #93, this PR is working in production so I propose merging it.  I can rebase if needed.

**Comment by jpic** [comment]
I'm sorry, it's a bit late and I got tempted to try the "resolve conflicts" button in github, but instead of a proper rebase it made a merge commit.

@claytondaley would you be interested in rebasing to have this in the next release ? do you still have this in production ?

**Comment by jpic** [comment]
Working here, merged manually, thanks!

**Pull request closed without merging**
